use_frameworks!

target 'AdyenBarcode_Example' do
  pod 'AdyenBarcoder', :path => '../'

  target 'AdyenBarcode_Tests' do
    inherit! :search_paths
    pod 'AdyenBarcoder', :path => '../'
    
  end
end
